### ISSUE TITLE
Cannot find namespace "WebMidi"

### ISSUE THREAD

**Issue by fazzitron** [OmniLlama/LAB-Assist#22]
I followed the steps as provided, but after running "ng serve", I get the error in the title:

Cannot find namespace "WebMidi"

I tried finding out how to install this, but can't find much.

**Comment by OmniLlama** [comment]
if I recall you from reddit, you may have still had the problem package I hadn't removed yet from the project on your first download, you could do one of the two things:

run `npm uninstall jzz` in terminal and retry serving, or
MAIN SOLUTION: delete your entire local project, redownload the latest main branch, and reinstall to remove the JZZ dependency (which has been a bit of a pain, honestly)

**Comment by fazzitron** [comment]
Yep, that's me, haha. Redownloading it fixed it! Time to play around!
